### ISSUE TITLE
EEEEEERRROOOOOOOOR OOOOON LOAAAAAAAD

### ISSUE THREAD

**Issue by noxerr** [ispikit/ispikit-unity#4]
Assets/Plugins/Ispikit.cs(164,67): error CS0176: Static member `Ispikit.playbackDoneCallback()' cannot be accessed with an instance reference, qualify it with a type name instead

Assets/Plugins/Ispikit.cs(163,59): error CS0176: Static member `Ispikit.newAudioCallback(int, string, string)' cannot be accessed with an instance reference, qualify it with a type name instead

Assets/Plugins/Ispikit.cs(162,59): error CS0176: Static member `Ispikit.newWordsCallback(string)' cannot be accessed with an instance reference, qualify it with a type name instead

Assets/Plugins/Ispikit.cs(161,63): error CS0176: Static member `Ispikit.completionCallback(int)' cannot be accessed with an instance reference, qualify it with a type name instead

Assets/Plugins/Ispikit.cs(160,55): error CS0176: Static member `Ispikit.resultCallback(int, int, string)' cannot be accessed with an instance reference, qualify it with a type name instead

**Comment by syl22-00** [comment]
I am treating this as spam, if that was not intended, please send a desciption of your issue in English.
